### ISSUE TITLE
ProjectRoot() not working in .py-files

### ISSUE THREAD

**Issue by akcssb** [statisticsnorway/ssb-fagfunksjoner#106]
ProjectRoot() from paths/project_root.py does not work when running from .py file. Only works when used from .ipynb

**Comment by aecorn** [comment]
You need to add more detail:
- Environment
- How are you executing the py files?
- Are you opening them "as Notebooks" in Jupyterlab?

**Comment by aecorn** [comment]
Works in my testing.
- Dapla Lab
- Percent-py file "opened as notebook"
- ProjectRoot().path returns folder one step out

Here is my testcode:
https://github.com/statisticsnorway/ssb-fagfunksjoner/blob/debug_projectroot_pyfiles/demos/project_root.py

Please provide more information about the situation where _it_ (what?) was not working.
